add missing include for QPainterPath
Otherwise this causes the following error to appear

PlotWidget.cpp: In member function 'void CPlotWidget::drawGrid(QPainter&)':
PlotWidget.cpp:1328:18: error: aggregate 'QPainterPath path' has incomplete type and cannot be defined
     1328 |     QPainterPath path;